stages:
  - test
  - deploy

test-code-job:
  tags: ["tag1"]
  stage: test
  script:
    - echo "Testing"

deploy-code-job:
  tags: ["tag1"]
  stage: deploy
  script:
    - echo "Deploying"
  environment: 
    name: ane21/venv
    PORT: 5000
