stages:
  - test
  - staging
  - production

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
#variables:
#  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
#cache:
#  paths:
#    - .cache/pip
#    - venv/

before_script:
  - python3 --version  # For debugging
  - python3 -m venv venv
  - source venv/bin/activate

test-code-job:
  tags: ["tag1"]
  image: python:3.10.0-alpine
  stage: test
  script:
    - echo "Testing"
    - pip install -r requirements.txt
    - python3 -m tests.test_query_processor

staging-code-job:
  tags: ["tag1"]
  stage: staging
  script:
    - echo "Staging"
    - export PORT=5000
    - (nohup gunicorn --config gunicorn_config.py wsgi:app > log.txt 2> log.txt &); 
  environment: "staging"

production-code-job:
#  tags: ["tag1"]
  stage: production
  image: ruby:latest
  before_script:
    - gem install dpl-heroku
  script:
    - echo "Production"
    - dpl --provider=heroku --app=hl1022-simplewebapp --api-key=$heroku_api_key
  environment: "production"

# need to uncomment lines 28, 47-49 when using shared runners
# need to comment out line 45 when using shared runners



  # IP CONFIG: 146.169.45.174
